# Generated by Django 5.1.7 on 2025-05-10 07:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement_type', models.CharField(choices=[('banner', '横幅广告'), ('sidebar', '侧边栏广告'), ('popup', '弹窗广告'), ('text', '文字广告')], default='banner', max_length=20, unique=True)),
                ('dimension', models.CharField(blank=True, max_length=20, null=True)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('active', '投放中'), ('ended', '已结束'), ('rejected', '已拒绝'), ('deleted', '已删除')], default='pending', max_length=20)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daily_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='ads/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='AdPlace.adplacement')),
            ],
        ),
    ]
