# Generated by Django 5.1.7 on 2025-05-10 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdManage', '0001_initial'),
        ('AdPlace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='AdManage.campaign', verbose_name='所属活动'),
        ),
    ]
