# Generated by Django 5.1.7 on 2025-05-10 10:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdPlace', '0002_ad_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='description',
            field=models.TextField(blank=True, verbose_name='广告描述'),
        ),
        migrations.AddField(
            model_name='ad',
            name='name',
            field=models.CharField(default='未命名广告', max_length=100, verbose_name='广告名称'),
        ),
        migrations.AddField(
            model_name='ad',
            name='target_url',
            field=models.URLField(default='http://example.com', verbose_name='目标链接'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
