# Generated by Django 5.1.7 on 2025-05-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdPlace', '0003_ad_description_ad_name_ad_target_url_alter_ad_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
