# Generated by Django 5.1.7 on 2025-05-10 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdAudit', '0001_initial'),
        ('AdPlace', '0002_ad_campaign'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', '通过'), ('reject', '拒绝')], max_length=10, verbose_name='审核结果')),
                ('reason', models.TextField(verbose_name='审核意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='审核时间')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdPlace.ad', verbose_name='广告')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '审核日志',
                'verbose_name_plural': '审核日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='AdAuditLog',
        ),
    ]
