# Generated by Django 5.1.7 on 2025-05-10 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdPlace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='AdPlace.ad')),
            ],
            options={
                'verbose_name': '广告展示',
                'verbose_name_plural': '广告展示',
            },
        ),
        migrations.CreateModel(
            name='AdClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='AdPlace.ad')),
                ('impression', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks', to='DataShow.adimpression')),
            ],
            options={
                'verbose_name': '广告点击',
                'verbose_name_plural': '广告点击',
            },
        ),
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='AdPlace.ad')),
            ],
            options={
                'verbose_name': '每日统计',
                'verbose_name_plural': '每日统计',
            },
        ),
        migrations.AddIndex(
            model_name='adimpression',
            index=models.Index(fields=['ad', 'timestamp'], name='DataShow_ad_ad_id_042846_idx'),
        ),
        migrations.AddIndex(
            model_name='adclick',
            index=models.Index(fields=['ad', 'timestamp'], name='DataShow_ad_ad_id_0fa433_idx'),
        ),
        migrations.AddIndex(
            model_name='dailystats',
            index=models.Index(fields=['ad', 'date'], name='DataShow_da_ad_id_c10e43_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailystats',
            unique_together={('ad', 'date')},
        ),
    ]
