# Generated by Django 5.1.7 on 2025-05-23 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_update_existing_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='audit_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='audit_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='device_info',
        ),
        migrations.RemoveField(
            model_name='user',
            name='register_ip',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reject_reason',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
