# Generated by Django 5.1.7 on 2025-05-23 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_remove_user_audit_status_remove_user_audit_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='audit_status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '已拒绝')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='audit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='device_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='register_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', '管理员'), ('advertiser', '广告主')], default='advertiser', max_length=20),
        ),
    ]
