# Generated by Django 5.1.7 on 2025-05-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicerequest',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='接收邮箱'),
        ),
    ]
