# Generated by Django 5.1.7 on 2025-05-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0002_invoicerequest_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('balance', '余额支付'), ('alipay', '支付宝'), ('wechat', '微信支付'), ('bank', '银行转账')], default='balance', max_length=20),
        ),
    ]
