# Generated by Django 5.1.7 on 2025-05-24 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0003_transaction_description_transaction_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='发票抬头')),
                ('tax_number', models.CharField(max_length=30, verbose_name='税号')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='地址')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='电话')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='开户银行')),
                ('bank_account', models.CharField(blank=True, max_length=30, null=True, verbose_name='银行账号')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_infos', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '发票信息',
                'verbose_name_plural': '发票信息',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(choices=[('normal', '增值税普通发票'), ('special', '增值税专用发票'), ('electronic', '电子发票')], default='normal', max_length=20, verbose_name='发票类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='发票金额')),
                ('title', models.CharField(max_length=100, verbose_name='发票抬头')),
                ('tax_number', models.CharField(max_length=30, verbose_name='税号')),
                ('content', models.CharField(default='广告服务费', max_length=100, verbose_name='发票内容')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已开具'), ('rejected', '已拒绝'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('email', models.EmailField(max_length=254, verbose_name='接收邮箱')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='邮寄地址')),
                ('contact_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='发票号码')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='开票日期')),
                ('express_company', models.CharField(blank=True, max_length=50, null=True, verbose_name='快递公司')),
                ('tracking_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='快递单号')),
                ('admin_remark', models.TextField(blank=True, null=True, verbose_name='管理员备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL, verbose_name='申请用户')),
                ('invoice_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Payment.invoiceinfo', verbose_name='发票信息')),
            ],
            options={
                'verbose_name': '发票',
                'verbose_name_plural': '发票',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Payment.invoice', verbose_name='发票')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='Payment.transaction', verbose_name='交易记录')),
            ],
            options={
                'verbose_name': '发票项目',
                'verbose_name_plural': '发票项目',
            },
        ),
        migrations.DeleteModel(
            name='InvoiceRequest',
        ),
    ]
