# Generated by Django 5.1.7 on 2025-05-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0004_invoiceinfo_invoice_invoiceitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_pdf',
            field=models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='电子发票PDF'),
        ),
    ]
